<a href="https://colab.research.google.com/github/supatsara2002/BasicProg_DataViz65/blob/main/Recap_4_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Slicing

In [ ]:
import numpy

In [ ]:
list_a = [[2,4,5,],[1,2,3],[9,8,7],[3,6,9]]
mat_a = numpy.array(list_a)
mat_a

array([[2, 4, 5],
       [1, 2, 3],
       [9, 8, 7],
       [3, 6, 9]])

In [ ]:
import numpy as np

In [ ]:
list_b = [[-1,-1,2,4,5,],[-2,-2,1,2,3],[-3,-3,9,8,7],[-4,-4,3,6,9]]
mat_b = np.array(list_b)
mat_b

array([[-1, -1,  2,  4,  5],
       [-2, -2,  1,  2,  3],
       [-3, -3,  9,  8,  7],
       [-4, -4,  3,  6,  9]])

## Quiz2

1. slice ค่าลบออกมาจาก ```mat_b```
2. slice ```[1,2,3]``` จาก ```mat_a```
3. slice ```[[1,3],[9,7],[3,9]]``` ออกมาจาก ```mat_b```




## 1. slice ค่าลบออกมาจาก ```mat_b```

In [ ]:
mat_b[:4,:2]

array([[-1, -1],
       [-2, -2],
       [-3, -3],
       [-4, -4]])

## 2. slice ```[1,2,3]``` จาก ```mat_a```

In [ ]:
mat_a[1:2]

array([[1, 2, 3]])

## 3. slice ```[[1,3],[9,7],[3,9]]``` ออกมาจาก ```mat_b```

In [ ]:
mat_b[1:,2::2]

array([[1, 3],
       [9, 7],
       [3, 9]])

## Function Print

In [ ]:
print()

In [ ]:
print('สวัสดี')

สวัสดี


In [ ]:
print('hello')
print('สวัสดี')

hello
สวัสดี


In [ ]:
print('hello',end=' ')
print('สวัสดี')

hello สวัสดี


In [ ]:
print('hello','สวัสดี',sep='\n')

hello
สวัสดี


## HW1

เขียน Function
แสดงความต่างของเวลา (Quiz1)
โดย input อยู่ในรูปแบบ ```'09:11:50 - 12:30:15'```

และทดลองรัน
* 09:11:50 - 12:30:15
* 13:41:07 - 20:00:18
* 00:00:00 - 23:59:59

### ```09:11:50 - 12:30:15```

In [ ]:
def time_m1(a1,a2,a3,b1,b2,b3):
    ab = ((b1*3600) + (b2*60) + b3) - ((a1*3600) + (a2*60) + a3)
    y = ab
    return y

print(f'ความแตกต่างของเวลาระหว่าง 09:11:50 - 12:30:15 คือ {time_m1(9,11,50,12,30,15)} วินาที') 

ความแตกต่างของเวลาระหว่าง 09:11:50 - 12:30:15 คือ 11905 วินาที


### ```13:41:07 - 20:00:18```

In [ ]:
def time_m2(c1,c2,c3,d1,d2,d3):
    cd = ((d1*3600) + (d2*60) + d3) - ((c1*3600) + (c2*60) + c3)
    y = cd
    return y

print(f'ความแตกต่างของเวลาระหว่าง 13:41:07 - 20:00:18 คือ {time_m2(13,41,7,20,0,18)} วินาที')

ความแตกต่างของเวลาระหว่าง 13:41:07 - 20:00:18 คือ 22751 วินาที


### ```00:00:00 - 23:59:59```

In [ ]:
def time_m3(e1,e2,e3,f1,f2,f3):
    ef = ((f1*3600) + (f2*60) + f3) - ((e1*3600) + (e2*60) + e3)
    y = ef
    return y

print(f'ความแตกต่างของเวลาระหว่าง 00:00:00 - 23:59:59 คือ {time_m2(0,0,0,23,59,59)} วินาที') 

ความแตกต่างของเวลาระหว่าง 00:00:00 - 23:59:59 คือ 86399 วินาที


In [1]:
input = '09:11:50 - 12:30:15'
input

'09:11:50 - 12:30:15'

In [3]:
input_split = input.split('-')
input_split

['09:11:50 ', ' 12:30:15']

In [4]:
starttimeSP = input_split[0].split(':')
endtimeSP = input_split[-1].split(':')
print(starttimeSP,endtimeSP,sep='\n')

['09', '11', '50 ']
[' 12', '30', '15']


In [13]:
def caculate_time(input):
    input_split = input.split('-')
    starttimeSP = input_split[0].split(':')
    endtimeSP = input_split[-1].split(':')

    starttime = 3600*int(starttimeSP[0]) + 60*int(starttimeSP[1]) + int(starttimeSP[2])
    endtime = 3600*int(endtimeSP[0]) + 60*int(endtimeSP[1]) + int(endtimeSP[2])

    print(f'ระยะเวลาระหว่าง {input_split[0]} และ {input_split[1]} ห่างกันเท่ากับ {endtime-starttime:,} วินาที')


In [14]:
caculate_time('09:11:50 - 12:30:15')

ระยะเวลาระหว่าง 09:11:50  และ  12:30:15 ห่างกันเท่ากับ 11,905 วินาที


In [15]:
caculate_time('13:41:07 - 20:00:18')

ระยะเวลาระหว่าง 13:41:07  และ  20:00:18 ห่างกันเท่ากับ 22,751 วินาที


In [16]:
caculate_time('00:00:00 - 23:59:59')

ระยะเวลาระหว่าง 00:00:00  และ  23:59:59 ห่างกันเท่ากับ 86,399 วินาที
