<a href="https://colab.research.google.com/github/supatsara2002/BasicProg_DataViz65/blob/main/Recap_4_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Slicing

In [1]:
import numpy

In [2]:
list_a = [[2,4,5,],[1,2,3],[9,8,7],[3,6,9]]
mat_a = numpy.array(list_a)
mat_a

array([[2, 4, 5],
       [1, 2, 3],
       [9, 8, 7],
       [3, 6, 9]])

In [3]:
import numpy as np

In [4]:
list_b = [[-1,-1,2,4,5,],[-2,-2,1,2,3],[-3,-3,9,8,7],[-4,-4,3,6,9]]
mat_b = np.array(list_b)
mat_b

array([[-1, -1,  2,  4,  5],
       [-2, -2,  1,  2,  3],
       [-3, -3,  9,  8,  7],
       [-4, -4,  3,  6,  9]])

## Quiz2

1. slice ค่าลบออกมาจาก ```mat_b```
2. slice ```[1,2,3]``` จาก ```mat_a```
3. slice ```[[1,3],[9,7],[3,9]]``` ออกมาจาก ```mat_b```




## 1. slice ค่าลบออกมาจาก ```mat_b```

In [5]:
mat_b[:4,:2]

array([[-1, -1],
       [-2, -2],
       [-3, -3],
       [-4, -4]])

## 2. slice ```[1,2,3]``` จาก ```mat_a```

In [6]:
mat_a[1:2]

array([[1, 2, 3]])

## 3. slice ```[[1,3],[9,7],[3,9]]``` ออกมาจาก ```mat_b```

In [7]:
mat_b[1:,2::2]

array([[1, 3],
       [9, 7],
       [3, 9]])

## Function Print

In [8]:
print()

In [9]:
print('สวัสดี')

สวัสดี


In [10]:
print('hello')
print('สวัสดี')

hello
สวัสดี


In [11]:
print('hello',end=' ')
print('สวัสดี')

hello สวัสดี


In [12]:
print('hello','สวัสดี',sep='\n')

hello
สวัสดี


## HW1

เขียน Function
แสดงความต่างของเวลา (Quiz1)
โดย input อยู่ในรูปแบบ ```'09:11:50 - 12:30:15'```

และทดลองรัน
* 09:11:50 - 12:30:15
* 13:41:07 - 20:00:18
* 00:00:00 - 23:59:59

### ```09:11:50 - 12:30:15```

In [13]:
def time_m1(a1,a2,a3,b1,b2,b3):
    ab = ((b1*3600) + (b2*60) + b3) - ((a1*3600) + (a2*60) + a3)
    y = ab
    return y

print(f'ความแตกต่างของเวลาระหว่าง 09:11:50 - 12:30:15 คือ {time_m1(9,11,50,12,30,15):,} วินาที') 

ความแตกต่างของเวลาระหว่าง 09:11:50 - 12:30:15 คือ 11,905 วินาที


### ```13:41:07 - 20:00:18```

In [14]:
def time_m2(c1,c2,c3,d1,d2,d3):
    cd = ((d1*3600) + (d2*60) + d3) - ((c1*3600) + (c2*60) + c3)
    y = cd
    return y

print(f'ความแตกต่างของเวลาระหว่าง 13:41:07 - 20:00:18 คือ {time_m2(13,41,7,20,0,18):,} วินาที')

ความแตกต่างของเวลาระหว่าง 13:41:07 - 20:00:18 คือ 22,751 วินาที


### ```00:00:00 - 23:59:59```

In [15]:
def time_m3(e1,e2,e3,f1,f2,f3):
    ef = ((f1*3600) + (f2*60) + f3) - ((e1*3600) + (e2*60) + e3)
    y = ef
    return y

print(f'ความแตกต่างของเวลาระหว่าง 00:00:00 - 23:59:59 คือ {time_m2(0,0,0,23,59,59):,} วินาที') 

ความแตกต่างของเวลาระหว่าง 00:00:00 - 23:59:59 คือ 86,399 วินาที


In [16]:
input = '09:11:50 - 12:30:15'
input

'09:11:50 - 12:30:15'

In [17]:
input_split = input.split('-')
input_split

['09:11:50 ', ' 12:30:15']

In [23]:
starttimeSP = input_split[0].split(':')
endtimeSP = input_split[-1].split(':')
print(starttimeSP,endtimeSP,sep='\n')

['09', '11', '50 ']
[' 12', '30', '15']


In [19]:
def caculate_time(input):
    input_split = input.split('-')
    starttimeSP = input_split[0].split(':')
    endtimeSP = input_split[-1].split(':')

    starttime = 3600*int(starttimeSP[0]) + 60*int(starttimeSP[1]) + int(starttimeSP[2])
    endtime = 3600*int(endtimeSP[0]) + 60*int(endtimeSP[1]) + int(endtimeSP[2])

    print(f'ระยะเวลาระหว่าง {input_split[0]} และ {input_split[1]} ห่างกันเท่ากับ {endtime-starttime:,} วินาที')


In [20]:
caculate_time('09:11:50 - 12:30:15')

ระยะเวลาระหว่าง 09:11:50  และ  12:30:15 ห่างกันเท่ากับ 11,905 วินาที


In [21]:
caculate_time('13:41:07 - 20:00:18')

ระยะเวลาระหว่าง 13:41:07  และ  20:00:18 ห่างกันเท่ากับ 22,751 วินาที


In [22]:
caculate_time('00:00:00 - 23:59:59')

ระยะเวลาระหว่าง 00:00:00  และ  23:59:59 ห่างกันเท่ากับ 86,399 วินาที


## Quiz3

เขียน function แสดงความต่างของเวลาโดย input อยู่ในรูปแบบ 'XX:YY:ZZ - AA:BB:CC'

และวนลูปแสดงผลของ input ต่อไปนี้

- '09:11:50 - 12:30:15'
- '13:41:07 - 20:00:18'
- '00:00:00 - 23:59:59'
- '18:04:11 - 00:00:00'
- '21:30:00 - 03:05:15'

ตัวอย่าง input '00:00:00-01:00:00'

output ช่วงระยะเวลาระหว่าง 00:00:00 ถึง 01:00:00 มีเวลาทั้งหมด 3,600 วินาที


In [44]:
def print_Time(time) :
      x = time
      a = x.split(' - ')
      start=a[0].split(':')
      end=a[1].split(':')
      
      starttime = int(start[0])*3600 + int(start[1])*60 + int(start[2])
      endtime = int(end[0])*3600+ int(end[1])*60 + int(end[2])
     
      if endtime > starttime:
        print(f'ช่วงระยะเวลาระหว่าง {a[0]} ถึง {a[1]} มีเวลาทั้งหมด {endtime - starttime:,} วินาที')
      else:
        print(f'ช่วงระยะเวลาระหว่าง {a[0]} ถึง {a[1]} มีเวลาทั้งหมด {(endtime+(24*60*60)) - starttime:,} วินาที')


In [47]:
for time in ['09:11:50 - 12:30:15','13:41:07 - 20:00:18','00:00:00 - 23:59:59','18:04:11 - 00:00:00','21:30:00 - 03:05:15']:
    T = time
    print_Time(T)

ช่วงระยะเวลาระหว่าง 09:11:50 ถึง 12:30:15 มีเวลาทั้งหมด 11,905 วินาที
ช่วงระยะเวลาระหว่าง 13:41:07 ถึง 20:00:18 มีเวลาทั้งหมด 22,751 วินาที
ช่วงระยะเวลาระหว่าง 00:00:00 ถึง 23:59:59 มีเวลาทั้งหมด 86,399 วินาที
ช่วงระยะเวลาระหว่าง 18:04:11 ถึง 00:00:00 มีเวลาทั้งหมด 21,349 วินาที
ช่วงระยะเวลาระหว่าง 21:30:00 ถึง 03:05:15 มีเวลาทั้งหมด 20,115 วินาที
